spring:
  application:
    name: activity-service

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/
      database: fitnessactivity

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

  exchange:
    name: fitness.exchange

  queue:
    name: activity.queue

  routing:
    key: activity.tracking