// src/pages/recmmendations/RecommendationPage.jsx
import React from 'react';
import { useRecommendations } from '../../hooks/useRecommendations';
import RecommendationCard from '../../components/recommendation/RecommendationCard';
import Loader from '../../components/common/Loader';

const RecommendationPage = () => {
  const { recommendations, isLoading, isError, refetch } = useRecommendations();

  return (
    <div className="page-wrapper">
      <div className="container">
        {/* Header */}
        <div style={{ marginBottom: '2rem', animation: 'fadeIn 0.4s ease' }}>
          <div className="section-header">
            <div>
              <h1 className="page-title">AI Insights</h1>
              <p className="page-subtitle">
                Personalized recommendations generated by your fitness AI
              </p>
            </div>
            <button
              onClick={refetch}
              style={{
                display: 'flex', alignItems: 'center', gap: '0.4rem',
                background: 'var(--bg-glass)',
                border: '1px solid var(--border-light)',
                borderRadius: 'var(--radius-md)',
                color: 'var(--text-secondary)',
                fontFamily: 'var(--font-sans)',
                fontSize: '0.8rem', fontWeight: 600,
                padding: '0.5rem 1rem', cursor: 'pointer',
                transition: 'all var(--transition-fast)',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--bg-glass-strong)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'var(--bg-glass)'; e.currentTarget.style.color = 'var(--text-secondary)'; }}
            >
              🔄 Refresh
            </button>
          </div>
        </div>

        {/* AI feature highlight */}
        <div style={{
          background: 'var(--gradient-card)',
          border: '1px solid var(--border-accent)',
          borderRadius: 'var(--radius-lg)',
          padding: '1.25rem 1.5rem',
          marginBottom: '2rem',
          display: 'flex',
          alignItems: 'center',
          gap: '1rem',
        }}>
          <div style={{
            width: 48, height: 48,
            borderRadius: 'var(--radius-md)',
            background: 'var(--gradient-primary)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '1.4rem',
            flexShrink: 0,
            animation: 'pulse-glow 2.5s ease-in-out infinite',
          }}>
            🤖
          </div>
          <div>
            <div style={{ fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.25rem' }}>
              AI-Powered Analysis
            </div>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', lineHeight: 1.5 }}>
              Each recommendation is generated after analyzing your workout — including intensity, duration, calories, and your personal fitness history.
            </p>
          </div>
        </div>

        {/* Content states */}
        {isLoading && <Loader message="Loading your AI recommendations..." />}

        {isError && (
          <div style={{
            background: 'rgba(239,68,68,0.07)',
            border: '1px solid rgba(239,68,68,0.2)',
            borderRadius: 'var(--radius-lg)',
            padding: '2rem',
            textAlign: 'center',
          }}>
            <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>⚠️</div>
            <p style={{ color: '#fca5a5', fontWeight: 600, marginBottom: '0.5rem' }}>
              Failed to load recommendations
            </p>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginBottom: '1.25rem' }}>
              Make sure you have logged some activities first.
            </p>
            <button
              onClick={refetch}
              style={{
                padding: '0.55rem 1.25rem',
                background: 'rgba(239,68,68,0.1)',
                border: '1px solid rgba(239,68,68,0.25)',
                borderRadius: 'var(--radius-md)',
                color: '#fca5a5',
                fontFamily: 'var(--font-sans)',
                fontSize: '0.875rem',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              Try Again
            </button>
          </div>
        )}

        {!isLoading && !isError && recommendations.length === 0 && (
          <div className="glass-card-static empty-state">
            <div className="empty-state-icon">🤖</div>
            <h3 className="empty-state-title">No recommendations yet</h3>
            <p className="empty-state-desc">
              Log some activities and our AI will generate personalized recommendations for you.
            </p>
          </div>
        )}

        {!isLoading && !isError && recommendations.length > 0 && (
          <>
            <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginBottom: '1.25rem' }}>
              {recommendations.length} recommendation{recommendations.length === 1 ? '' : 's'} generated
            </p>
            <div className="grid-auto stagger-children">
              {recommendations.map((rec, i) => (
                <RecommendationCard key={rec.id || i} recommendation={rec} />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default RecommendationPage;